// === relation: Character -> Character ===
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_004'}) MERGE (a)-[:relation {type: '恋爱', detail: '已分手'}]->(b);
MATCH (a:Character {id: 'char_001'}), (b:Character {id: 'char_008'}) MERGE (a)-[:relation {type: '一夜情', detail: '陆择的一夜情对象'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_006'}) MERGE (a)-[:relation {type: '客户', detail: '代练客户'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_005'}) MERGE (a)-[:relation {type: '朋友', detail: '晨跑认识'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_007'}) MERGE (a)-[:relation {type: '上下级', detail: '战队经理与选手'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_009'}) MERGE (a)-[:relation {type: '冲突', detail: '试训时发生冲突'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Character {id: 'char_009'}) MERGE (a)-[:relation {type: '同事', detail: '战队经理与队长'}]->(b);

// === involved: Character -> Event ===
MATCH (a:Character {id: 'char_001'}), (b:Event {id: 'evt_001'}) MERGE (a)-[:involved {role: '当事人', detail: '酒店醒来逃离'}]->(b);
MATCH (a:Character {id: 'char_008'}), (b:Event {id: 'evt_001'}) MERGE (a)-[:involved {role: '参与者', detail: '穿白衬衫洗漱准备离开'}]->(b);
MATCH (a:Character {id: 'char_001'}), (b:Event {id: 'evt_002'}) MERGE (a)-[:involved {role: '当事人', detail: '遭遇车祸死亡'}]->(b);
MATCH (a:Character {id: 'char_002'}), (b:Event {id: 'evt_003'}) MERGE (a)-[:involved {role: '当事人', detail: '告知试炼规则'}]->(b);
MATCH (a:Character {id: 'char_001'}), (b:Event {id: 'evt_003'}) MERGE (a)-[:involved {role: '参与者', detail: '被告知规则'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_004'}) MERGE (a)-[:involved {role: '当事人', detail: '跳江时被灵魂挤入'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_005'}) MERGE (a)-[:involved {role: '当事人', detail: '分支A接到姐姐电话'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_006'}) MERGE (a)-[:involved {role: '当事人', detail: '分支B跳江BE'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_007'}) MERGE (a)-[:involved {role: '当事人', detail: '发现转账记录并删微信'}]->(b);
MATCH (a:Character {id: 'char_004'}), (b:Event {id: 'evt_007'}) MERGE (a)-[:involved {role: '涉及者', detail: '转账收款人'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_008'}) MERGE (a)-[:involved {role: '当事人', detail: '步行回出租屋发现身体损耗'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_009'}) MERGE (a)-[:involved {role: '当事人', detail: '理发买衣吃面'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_010'}) MERGE (a)-[:involved {role: '当事人', detail: '重返代练'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_010'}) MERGE (a)-[:involved {role: '参与者', detail: '点单被实力折服'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_011'}) MERGE (a)-[:involved {role: '当事人', detail: '晨跑'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_011'}) MERGE (a)-[:involved {role: '参与者', detail: '指出跑步姿势问题'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_012'}) MERGE (a)-[:involved {role: '当事人', detail: '做直播'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_012'}) MERGE (a)-[:involved {role: '参与者', detail: '提议做直播'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_013'}) MERGE (a)-[:involved {role: '当事人', detail: '收到私信'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_013'}) MERGE (a)-[:involved {role: '参与者', detail: '发私信联系'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_014'}) MERGE (a)-[:involved {role: '当事人', detail: '参加试训'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_014'}) MERGE (a)-[:involved {role: '参与者', detail: '安排试训'}]->(b);
MATCH (a:Character {id: 'char_009'}), (b:Event {id: 'evt_014'}) MERGE (a)-[:involved {role: '参与者', detail: '与陈默冲突'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_015'}) MERGE (a)-[:involved {role: '当事人', detail: '被邀请'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_015'}) MERGE (a)-[:involved {role: '参与者', detail: '邀请加入二队'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_016'}) MERGE (a)-[:involved {role: '当事人', detail: '被拉去吃牛排'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_016'}) MERGE (a)-[:involved {role: '参与者', detail: '看到签名后拉人'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_017'}) MERGE (a)-[:involved {role: '当事人', detail: '跑步遇雨'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_017'}) MERGE (a)-[:involved {role: '参与者', detail: '一起避雨'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_018'}) MERGE (a)-[:involved {role: '当事人', detail: '冰箱被搜'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_018'}) MERGE (a)-[:involved {role: '参与者', detail: '拉人去超市'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_019'}) MERGE (a)-[:involved {role: '参与者', detail: '直播中'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_019'}) MERGE (a)-[:involved {role: '当事人', detail: '房管对喷弹幕'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_020'}) MERGE (a)-[:involved {role: '当事人', detail: '爬山'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_020'}) MERGE (a)-[:involved {role: '参与者', detail: '一起爬山'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_021'}) MERGE (a)-[:involved {role: '当事人', detail: '地铁返程'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_021'}) MERGE (a)-[:involved {role: '参与者', detail: '睡着靠过来'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_022'}) MERGE (a)-[:involved {role: '当事人', detail: '被拉去漫展'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_022'}) MERGE (a)-[:involved {role: '参与者', detail: '拉人去漫展'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_023'}) MERGE (a)-[:involved {role: '当事人', detail: '送人回家'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_023'}) MERGE (a)-[:involved {role: '参与者', detail: '被送回家'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_024'}) MERGE (a)-[:involved {role: '当事人', detail: '生病发烧'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_024'}) MERGE (a)-[:involved {role: '参与者', detail: '送吃的'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_025'}) MERGE (a)-[:involved {role: '当事人', detail: '拉人去路边摊'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_025'}) MERGE (a)-[:involved {role: '参与者', detail: '被辣出眼泪'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_026'}) MERGE (a)-[:involved {role: '当事人', detail: '偷偷去看人'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_026'}) MERGE (a)-[:involved {role: '参与者', detail: '被偷看'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_027'}) MERGE (a)-[:involved {role: '当事人', detail: '面临三选一'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_027'}) MERGE (a)-[:involved {role: '参与者', detail: '未接来电方'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_027'}) MERGE (a)-[:involved {role: '参与者', detail: '未接来电方'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_027'}) MERGE (a)-[:involved {role: '参与者', detail: '未接来电方'}]->(b);

// === occurred_at: Event -> Scene ===
MATCH (a:Event {id: 'evt_001'}), (b:Scene {id: 'scene_001'}) MERGE (a)-[:occurred_at {detail: '陆择醒来的酒店'}]->(b);
MATCH (a:Event {id: 'evt_002'}), (b:Scene {id: 'scene_002'}) MERGE (a)-[:occurred_at {detail: '车祸地点'}]->(b);
MATCH (a:Event {id: 'evt_004'}), (b:Scene {id: 'scene_003'}) MERGE (a)-[:occurred_at {detail: '跳江地点'}]->(b);
MATCH (a:Event {id: 'evt_007'}), (b:Scene {id: 'scene_003'}) MERGE (a)-[:occurred_at {detail: '在大桥上查看手机'}]->(b);
MATCH (a:Event {id: 'evt_008'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '回到出租屋'}]->(b);
MATCH (a:Event {id: 'evt_009'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '从出租屋出发'}]->(b);
MATCH (a:Event {id: 'evt_010'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '在出租屋代练'}]->(b);
MATCH (a:Event {id: 'evt_011'}), (b:Scene {id: 'scene_005'}) MERGE (a)-[:occurred_at {detail: '晨跑地点'}]->(b);
MATCH (a:Event {id: 'evt_012'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '在出租屋直播'}]->(b);
MATCH (a:Event {id: 'evt_013'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '在出租屋收私信'}]->(b);
MATCH (a:Event {id: 'evt_014'}), (b:Scene {id: 'scene_015'}) MERGE (a)-[:occurred_at {detail: '试训地点'}]->(b);
MATCH (a:Event {id: 'evt_015'}), (b:Scene {id: 'scene_006'}) MERGE (a)-[:occurred_at {detail: '咖啡店约谈'}]->(b);
MATCH (a:Event {id: 'evt_016'}), (b:Scene {id: 'scene_007'}) MERGE (a)-[:occurred_at {detail: '西餐厅吃牛排'}]->(b);
MATCH (a:Event {id: 'evt_017'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '回出租屋避雨'}]->(b);
MATCH (a:Event {id: 'evt_018'}), (b:Scene {id: 'scene_014'}) MERGE (a)-[:occurred_at {detail: '去买菜'}]->(b);
MATCH (a:Event {id: 'evt_019'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '在出租屋直播'}]->(b);
MATCH (a:Event {id: 'evt_020'}), (b:Scene {id: 'scene_008'}) MERGE (a)-[:occurred_at {detail: '爬山'}]->(b);
MATCH (a:Event {id: 'evt_021'}), (b:Scene {id: 'scene_009'}) MERGE (a)-[:occurred_at {detail: '地铁返程'}]->(b);
MATCH (a:Event {id: 'evt_022'}), (b:Scene {id: 'scene_010'}) MERGE (a)-[:occurred_at {detail: '漫展'}]->(b);
MATCH (a:Event {id: 'evt_023'}), (b:Scene {id: 'scene_011'}) MERGE (a)-[:occurred_at {detail: '送林梦回家'}]->(b);
MATCH (a:Event {id: 'evt_024'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '在出租屋生病'}]->(b);
MATCH (a:Event {id: 'evt_025'}), (b:Scene {id: 'scene_012'}) MERGE (a)-[:occurred_at {detail: '路边摊'}]->(b);
MATCH (a:Event {id: 'evt_026'}), (b:Scene {id: 'scene_013'}) MERGE (a)-[:occurred_at {detail: '苏晓禾工作地点'}]->(b);
MATCH (a:Event {id: 'evt_027'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '在出租屋接电话'}]->(b);

// === at: Character -> Scene ===
MATCH (a:Character {id: 'char_003'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:at {type: '居住', detail: '陈默的八楼出租屋'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Scene {id: 'scene_011'}) MERGE (a)-[:at {type: '居住', detail: '林梦的超级大平层'}]->(b);
MATCH (a:Character {id: 'char_009'}), (b:Scene {id: 'scene_015'}) MERGE (a)-[:at {type: '工作', detail: '星耀电竞战队队长'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Scene {id: 'scene_015'}) MERGE (a)-[:at {type: '工作', detail: '星耀电竞战队经理'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Scene {id: 'scene_013'}) MERGE (a)-[:at {type: '工作', detail: '运动康复师工作地点'}]->(b);

// === link: Character/Event/Scene/Info -> Info ===
MATCH (a:Character {id: 'char_001'}), (b:Info {id: 'info_001'}) MERGE (a)-[:link {type: '涉及', detail: '灵魂穿越者能力'}]->(b);
MATCH (a:Character {id: 'char_001'}), (b:Info {id: 'info_002'}) MERGE (a)-[:link {type: '涉及', detail: '灵魂穿越者限制'}]->(b);
MATCH (a:Character {id: 'char_002'}), (b:Info {id: 'info_003'}) MERGE (a)-[:link {type: '涉及', detail: '伊芙告知试炼规则'}]->(b);
MATCH (a:Event {id: 'evt_003'}), (b:Info {id: 'info_003'}) MERGE (a)-[:link {type: '涉及', detail: '告知规则事件'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Info {id: 'info_004'}) MERGE (a)-[:link {type: '涉及', detail: '转账付款人'}]->(b);
MATCH (a:Character {id: 'char_004'}), (b:Info {id: 'info_004'}) MERGE (a)-[:link {type: '涉及', detail: '转账收款人'}]->(b);
MATCH (a:Event {id: 'evt_007'}), (b:Info {id: 'info_004'}) MERGE (a)-[:link {type: '涉及', detail: '发现转账记录'}]->(b);
MATCH (a:Event {id: 'evt_008'}), (b:Info {id: 'info_005'}) MERGE (a)-[:link {type: '涉及', detail: '发现身体损耗'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Info {id: 'info_005'}) MERGE (a)-[:link {type: '涉及', detail: '身体损耗的主人'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Info {id: 'info_006'}) MERGE (a)-[:link {type: '涉及', detail: '富家千金'}]->(b);
MATCH (a:Event {id: 'evt_023'}), (b:Info {id: 'info_006'}) MERGE (a)-[:link {type: '涉及', detail: '送林梦回家发现家境'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Info {id: 'info_007'}) MERGE (a)-[:link {type: '涉及', detail: '林梦自述童年'}]->(b);
MATCH (a:Event {id: 'evt_023'}), (b:Info {id: 'info_007'}) MERGE (a)-[:link {type: '涉及', detail: '送林梦回家时对话'}]->(b);
MATCH (a:Event {id: 'evt_014'}), (b:Info {id: 'info_008'}) MERGE (a)-[:link {type: '涉及', detail: '试训表现'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Info {id: 'info_008'}) MERGE (a)-[:link {type: '涉及', detail: '试训当事人'}]->(b);
MATCH (a:Character {id: 'char_009'}), (b:Info {id: 'info_008'}) MERGE (a)-[:link {type: '涉及', detail: '冲突对象'}]->(b);
MATCH (a:Event {id: 'evt_012'}), (b:Info {id: 'info_009'}) MERGE (a)-[:link {type: '涉及', detail: '直播数据'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Info {id: 'info_009'}) MERGE (a)-[:link {type: '涉及', detail: '直播提议者'}]->(b);
MATCH (a:Event {id: 'evt_015'}), (b:Info {id: 'info_010'}) MERGE (a)-[:link {type: '涉及', detail: '邀请加入二队'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Info {id: 'info_010'}) MERGE (a)-[:link {type: '涉及', detail: '邀请方'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Info {id: 'info_010'}) MERGE (a)-[:link {type: '涉及', detail: '被邀请者'}]->(b);

// === evt_relation: Event -> Event ===
MATCH (a:Event {id: 'evt_001'}), (b:Event {id: 'evt_002'}) MERGE (a)-[:evt_relation {type: '因果', detail: '逃离酒店后过马路遭遇车祸'}]->(b);
MATCH (a:Event {id: 'evt_002'}), (b:Event {id: 'evt_003'}) MERGE (a)-[:evt_relation {type: '因果', detail: '死亡后见到伊芙被告知规则'}]->(b);
MATCH (a:Event {id: 'evt_003'}), (b:Event {id: 'evt_004'}) MERGE (a)-[:evt_relation {type: '因果', detail: '试炼开始进入陈默身体'}]->(b);
MATCH (a:Event {id: 'evt_004'}), (b:Event {id: 'evt_005'}) MERGE (a)-[:evt_relation {type: '包含', detail: '分支A（主线）'}]->(b);
MATCH (a:Event {id: 'evt_004'}), (b:Event {id: 'evt_006'}) MERGE (a)-[:evt_relation {type: '包含', detail: '分支B（BE）'}]->(b);
MATCH (a:Event {id: 'evt_004'}), (b:Event {id: 'evt_007'}) MERGE (a)-[:evt_relation {type: '先后', detail: '灵魂挤入后检查手机发现转账'}]->(b);
MATCH (a:Event {id: 'evt_007'}), (b:Event {id: 'evt_008'}) MERGE (a)-[:evt_relation {type: '先后', detail: '删微信后步行回出租屋'}]->(b);
MATCH (a:Event {id: 'evt_008'}), (b:Event {id: 'evt_009'}) MERGE (a)-[:evt_relation {type: '先后', detail: '回出租屋后整理自己'}]->(b);
MATCH (a:Event {id: 'evt_009'}), (b:Event {id: 'evt_010'}) MERGE (a)-[:evt_relation {type: '先后', detail: '整理完毕后重返代练'}]->(b);
MATCH (a:Event {id: 'evt_010'}), (b:Event {id: 'evt_011'}) MERGE (a)-[:evt_relation {type: '先后', detail: '代练稳定后开始晨跑'}]->(b);
MATCH (a:Event {id: 'evt_010'}), (b:Event {id: 'evt_012'}) MERGE (a)-[:evt_relation {type: '先后', detail: '代练积累粉丝后开始直播'}]->(b);
MATCH (a:Event {id: 'evt_012'}), (b:Event {id: 'evt_013'}) MERGE (a)-[:evt_relation {type: '先后', detail: '下播后收私信'}]->(b);
MATCH (a:Event {id: 'evt_013'}), (b:Event {id: 'evt_014'}) MERGE (a)-[:evt_relation {type: '因果', detail: '私信联系后参加试训'}]->(b);
MATCH (a:Event {id: 'evt_014'}), (b:Event {id: 'evt_015'}) MERGE (a)-[:evt_relation {type: '先后', detail: '试训后约谈邀请'}]->(b);
MATCH (a:Event {id: 'evt_015'}), (b:Event {id: 'evt_016'}) MERGE (a)-[:evt_relation {type: '先后', detail: '加入后建立私交'}]->(b);
MATCH (a:Event {id: 'evt_016'}), (b:Event {id: 'evt_017'}) MERGE (a)-[:evt_relation {type: '先后', detail: '感情线推进'}]->(b);
MATCH (a:Event {id: 'evt_017'}), (b:Event {id: 'evt_018'}) MERGE (a)-[:evt_relation {type: '先后', detail: '同一天上午避雨后下午买菜'}]->(b);
MATCH (a:Event {id: 'evt_020'}), (b:Event {id: 'evt_021'}) MERGE (a)-[:evt_relation {type: '先后', detail: '同一天爬山后地铁返程'}]->(b);
MATCH (a:Event {id: 'evt_022'}), (b:Event {id: 'evt_023'}) MERGE (a)-[:evt_relation {type: '先后', detail: '同一天漫展后送人回家'}]->(b);
MATCH (a:Event {id: 'evt_024'}), (b:Event {id: 'evt_025'}) MERGE (a)-[:evt_relation {type: '先后', detail: '生病后社交恢复'}]->(b);
MATCH (a:Event {id: 'evt_025'}), (b:Event {id: 'evt_026'}) MERGE (a)-[:evt_relation {type: '先后', detail: '社交推进'}]->(b);
MATCH (a:Event {id: 'evt_026'}), (b:Event {id: 'evt_027'}) MERGE (a)-[:evt_relation {type: '先后', detail: '感情升温后面临抉择'}]->(b);
