// ========== relation: Character → Character ==========
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_004'}) MERGE (a)-[:relation {type: '恋爱', detail: '陈默前女友·已分手'}]->(b);
MATCH (a:Character {id: 'char_002'}), (b:Character {id: 'char_001'}) MERGE (a)-[:relation {type: '引导', detail: '灵魂引路人与穿越者'}]->(b);
MATCH (a:Character {id: 'char_001'}), (b:Character {id: 'char_008'}) MERGE (a)-[:relation {type: '一夜情', detail: '开场前'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_005'}) MERGE (a)-[:relation {type: '暧昧', detail: '晨跑偶遇后逐渐升温', start_time: 'Day 4'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_006'}) MERGE (a)-[:relation {type: '客户', detail: '代练关系·后成小迷妹', start_time: 'Day 2'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_007'}) MERGE (a)-[:relation {type: '职业', detail: '沈暮雪邀请男主加入战队', start_time: 'Day 5'}]->(b);
MATCH (a:Character {id: 'char_009'}), (b:Character {id: 'char_007'}) MERGE (a)-[:relation {type: '同事', detail: '战队队长与经理'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Character {id: 'char_009'}) MERGE (a)-[:relation {type: '冲突', detail: '试训中发生冲突', start_time: 'Day 7'}]->(b);

// ========== involved: Character → Event ==========
MATCH (a:Character {id: 'char_001'}), (b:Event {id: 'evt_001'}) MERGE (a)-[:involved {role: '当事人', detail: '酒店醒来逃离'}]->(b);
MATCH (a:Character {id: 'char_008'}), (b:Event {id: 'evt_001'}) MERGE (a)-[:involved {role: '参与者', detail: '洗漱准备离开'}]->(b);
MATCH (a:Character {id: 'char_001'}), (b:Event {id: 'evt_002'}) MERGE (a)-[:involved {role: '当事人', detail: '车祸死亡'}]->(b);
MATCH (a:Character {id: 'char_001'}), (b:Event {id: 'evt_003'}) MERGE (a)-[:involved {role: '参与者', detail: '被告知试炼规则'}]->(b);
MATCH (a:Character {id: 'char_002'}), (b:Event {id: 'evt_003'}) MERGE (a)-[:involved {role: '当事人', detail: '告知试炼规则'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_004'}) MERGE (a)-[:involved {role: '当事人', detail: '跳江被陆择灵魂挤入身体'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_005'}) MERGE (a)-[:involved {role: '当事人', detail: '姐姐来电'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_006'}) MERGE (a)-[:involved {role: '当事人', detail: '跳江BE'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_007'}) MERGE (a)-[:involved {role: '当事人', detail: '发现转账记录删温蔓青微信'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_008'}) MERGE (a)-[:involved {role: '当事人', detail: '步行回出租屋'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_009'}) MERGE (a)-[:involved {role: '当事人', detail: '理发买衣吃面'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_010'}) MERGE (a)-[:involved {role: '当事人', detail: '重返代练'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_010'}) MERGE (a)-[:involved {role: '参与者', detail: '林梦点单'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_011'}) MERGE (a)-[:involved {role: '当事人', detail: '晨跑偶遇苏晓禾'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_011'}) MERGE (a)-[:involved {role: '参与者', detail: '偶遇'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_012'}) MERGE (a)-[:involved {role: '当事人', detail: '做直播'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_012'}) MERGE (a)-[:involved {role: '参与者', detail: '提议做直播'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_013'}) MERGE (a)-[:involved {role: '当事人', detail: '收到私信'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_013'}) MERGE (a)-[:involved {role: '参与者', detail: '发私信'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_014'}) MERGE (a)-[:involved {role: '当事人', detail: '试训'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_014'}) MERGE (a)-[:involved {role: '参与者', detail: '观察试训'}]->(b);
MATCH (a:Character {id: 'char_009'}), (b:Event {id: 'evt_014'}) MERGE (a)-[:involved {role: '参与者', detail: '试训冲突对象'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_015'}) MERGE (a)-[:involved {role: '当事人', detail: '被约见'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_015'}) MERGE (a)-[:involved {role: '当事人', detail: '约见邀请加入二队'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_016'}) MERGE (a)-[:involved {role: '当事人', detail: '被拉去西餐厅'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_016'}) MERGE (a)-[:involved {role: '当事人', detail: '拉男主去西餐厅'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_017'}) MERGE (a)-[:involved {role: '当事人', detail: '出租屋避雨'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_017'}) MERGE (a)-[:involved {role: '参与者', detail: '出租屋避雨'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_018'}) MERGE (a)-[:involved {role: '当事人', detail: '被拉去超市'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_018'}) MERGE (a)-[:involved {role: '当事人', detail: '拉男主去超市'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_019'}) MERGE (a)-[:involved {role: '当事人', detail: '直播中'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_019'}) MERGE (a)-[:involved {role: '当事人', detail: '房管对喷弹幕'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_020'}) MERGE (a)-[:involved {role: '当事人', detail: '爬山'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_020'}) MERGE (a)-[:involved {role: '参与者', detail: '一起爬山'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_021'}) MERGE (a)-[:involved {role: '当事人', detail: '地铁返程'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_021'}) MERGE (a)-[:involved {role: '参与者', detail: '靠过来睡着'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_022'}) MERGE (a)-[:involved {role: '当事人', detail: '被拉去漫展'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_022'}) MERGE (a)-[:involved {role: '当事人', detail: '拉男主去漫展'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_023'}) MERGE (a)-[:involved {role: '当事人', detail: '送林梦回家'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_023'}) MERGE (a)-[:involved {role: '当事人', detail: '被送回家'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_024'}) MERGE (a)-[:involved {role: '当事人', detail: '生病发烧'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_024'}) MERGE (a)-[:involved {role: '参与者', detail: '送吃的'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_025'}) MERGE (a)-[:involved {role: '当事人', detail: '拉沈暮雪去路边摊'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_025'}) MERGE (a)-[:involved {role: '参与者', detail: '被拉去路边摊'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_026'}) MERGE (a)-[:involved {role: '当事人', detail: '偷偷看苏晓禾'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_026'}) MERGE (a)-[:involved {role: '参与者', detail: '被偷看'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_027'}) MERGE (a)-[:involved {role: '当事人', detail: '三选一'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_027'}) MERGE (a)-[:involved {role: '参与者', detail: '三选一候选'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_027'}) MERGE (a)-[:involved {role: '参与者', detail: '三选一候选'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_027'}) MERGE (a)-[:involved {role: '参与者', detail: '三选一候选'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_028'}) MERGE (a)-[:involved {role: '当事人', detail: '苏晓禾结局线'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Event {id: 'evt_028'}) MERGE (a)-[:involved {role: '当事人', detail: '苏晓禾结局线'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_029'}) MERGE (a)-[:involved {role: '当事人', detail: '林梦结局线'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Event {id: 'evt_029'}) MERGE (a)-[:involved {role: '当事人', detail: '林梦结局线'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Event {id: 'evt_030'}) MERGE (a)-[:involved {role: '当事人', detail: '沈暮雪结局线'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Event {id: 'evt_030'}) MERGE (a)-[:involved {role: '当事人', detail: '沈暮雪结局线'}]->(b);

// ========== occurred_at: Event → Scene ==========
MATCH (a:Event {id: 'evt_001'}), (b:Scene {id: 'scene_001'}) MERGE (a)-[:occurred_at {detail: '酒店开场'}]->(b);
MATCH (a:Event {id: 'evt_004'}), (b:Scene {id: 'scene_002'}) MERGE (a)-[:occurred_at {detail: '跳江地点'}]->(b);
MATCH (a:Event {id: 'evt_008'}), (b:Scene {id: 'scene_003'}) MERGE (a)-[:occurred_at {detail: '步行回出租屋'}]->(b);
MATCH (a:Event {id: 'evt_011'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:occurred_at {detail: '南滨路晨跑'}]->(b);
MATCH (a:Event {id: 'evt_014'}), (b:Scene {id: 'scene_005'}) MERGE (a)-[:occurred_at {detail: '试训地点'}]->(b);
MATCH (a:Event {id: 'evt_015'}), (b:Scene {id: 'scene_006'}) MERGE (a)-[:occurred_at {detail: '咖啡店约见'}]->(b);
MATCH (a:Event {id: 'evt_016'}), (b:Scene {id: 'scene_007'}) MERGE (a)-[:occurred_at {detail: '西餐厅约会'}]->(b);
MATCH (a:Event {id: 'evt_017'}), (b:Scene {id: 'scene_003'}) MERGE (a)-[:occurred_at {detail: '出租屋避雨'}]->(b);
MATCH (a:Event {id: 'evt_018'}), (b:Scene {id: 'scene_008'}) MERGE (a)-[:occurred_at {detail: '超市购物'}]->(b);
MATCH (a:Event {id: 'evt_020'}), (b:Scene {id: 'scene_013'}) MERGE (a)-[:occurred_at {detail: '爬山'}]->(b);
MATCH (a:Event {id: 'evt_021'}), (b:Scene {id: 'scene_012'}) MERGE (a)-[:occurred_at {detail: '地铁返程'}]->(b);
MATCH (a:Event {id: 'evt_022'}), (b:Scene {id: 'scene_009'}) MERGE (a)-[:occurred_at {detail: '漫展'}]->(b);
MATCH (a:Event {id: 'evt_023'}), (b:Scene {id: 'scene_010'}) MERGE (a)-[:occurred_at {detail: '送林梦回家'}]->(b);
MATCH (a:Event {id: 'evt_024'}), (b:Scene {id: 'scene_003'}) MERGE (a)-[:occurred_at {detail: '出租屋养病'}]->(b);
MATCH (a:Event {id: 'evt_025'}), (b:Scene {id: 'scene_011'}) MERGE (a)-[:occurred_at {detail: '路边摊'}]->(b);

// ========== at: Character → Scene ==========
MATCH (a:Character {id: 'char_003'}), (b:Scene {id: 'scene_003'}) MERGE (a)-[:at {type: '居住', detail: '陈默的住所'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Scene {id: 'scene_004'}) MERGE (a)-[:at {type: '前往', detail: '晨跑'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Scene {id: 'scene_010'}) MERGE (a)-[:at {type: '居住', detail: '超级大平层'}]->(b);
MATCH (a:Character {id: 'char_007'}), (b:Scene {id: 'scene_005'}) MERGE (a)-[:at {type: '工作', detail: '战队经理'}]->(b);
MATCH (a:Character {id: 'char_009'}), (b:Scene {id: 'scene_005'}) MERGE (a)-[:at {type: '工作', detail: '战队队长'}]->(b);

// ========== link: Entity → Info ==========
MATCH (a:Character {id: 'char_001'}), (b:Info {id: 'info_001'}) MERGE (a)-[:link {type: '涉及', detail: '陆择作为灵魂穿越者的能力'}]->(b);
MATCH (a:Character {id: 'char_001'}), (b:Info {id: 'info_002'}) MERGE (a)-[:link {type: '涉及', detail: '陆择只能在关键节点干预'}]->(b);
MATCH (a:Character {id: 'char_002'}), (b:Info {id: 'info_003'}) MERGE (a)-[:link {type: '涉及', detail: '伊芙告知试炼规则'}]->(b);
MATCH (a:Event {id: 'evt_003'}), (b:Info {id: 'info_003'}) MERGE (a)-[:link {type: '涉及', detail: '事件中告知规则'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Info {id: 'info_004'}) MERGE (a)-[:link {type: '涉及', detail: '陈默转账给温蔓青'}]->(b);
MATCH (a:Character {id: 'char_004'}), (b:Info {id: 'info_004'}) MERGE (a)-[:link {type: '涉及', detail: '温蔓青收钱'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Info {id: 'info_005'}) MERGE (a)-[:link {type: '涉及', detail: '陈默身体状况'}]->(b);
MATCH (a:Event {id: 'evt_008'}), (b:Info {id: 'info_005'}) MERGE (a)-[:link {type: '涉及', detail: '步行回家发现身体损耗'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Info {id: 'info_006'}) MERGE (a)-[:link {type: '涉及', detail: '苏晓禾职业'}]->(b);
MATCH (a:Event {id: 'evt_011'}), (b:Info {id: 'info_006'}) MERGE (a)-[:link {type: '涉及', detail: '偶遇时得知'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Info {id: 'info_007'}) MERGE (a)-[:link {type: '涉及', detail: '林梦被代练实力折服'}]->(b);
MATCH (a:Event {id: 'evt_010'}), (b:Info {id: 'info_007'}) MERGE (a)-[:link {type: '涉及', detail: '代练事件'}]->(b);
MATCH (a:Event {id: 'evt_014'}), (b:Info {id: 'info_008'}) MERGE (a)-[:link {type: '涉及', detail: '试训中表现'}]->(b);
MATCH (a:Character {id: 'char_009'}), (b:Info {id: 'info_008'}) MERGE (a)-[:link {type: '涉及', detail: '与男主配合问题'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Info {id: 'info_009'}) MERGE (a)-[:link {type: '涉及', detail: '林梦家境'}]->(b);
MATCH (a:Event {id: 'evt_023'}), (b:Info {id: 'info_009'}) MERGE (a)-[:link {type: '涉及', detail: '送回家时发现'}]->(b);
MATCH (a:Character {id: 'char_006'}), (b:Info {id: 'info_010'}) MERGE (a)-[:link {type: '涉及', detail: '林梦童年'}]->(b);
MATCH (a:Event {id: 'evt_023'}), (b:Info {id: 'info_010'}) MERGE (a)-[:link {type: '涉及', detail: '送回家时得知'}]->(b);
MATCH (a:Character {id: 'char_005'}), (b:Info {id: 'info_011'}) MERGE (a)-[:link {type: '涉及', detail: '苏晓禾对男主有好感'}]->(b);
MATCH (a:Event {id: 'evt_018'}), (b:Info {id: 'info_011'}) MERGE (a)-[:link {type: '涉及', detail: '被说像老夫老妻时耳朵红了'}]->(b);
MATCH (a:Event {id: 'evt_014'}), (b:Info {id: 'info_012'}) MERGE (a)-[:link {type: '涉及', detail: '试训时冲突'}]->(b);
MATCH (a:Character {id: 'char_003'}), (b:Info {id: 'info_012'}) MERGE (a)-[:link {type: '涉及', detail: '男主与江烈'}]->(b);
MATCH (a:Character {id: 'char_009'}), (b:Info {id: 'info_012'}) MERGE (a)-[:link {type: '涉及', detail: '江烈与男主'}]->(b);
MATCH (a:Info {id: 'info_009'}), (b:Info {id: 'info_010'}) MERGE (a)-[:link {type: '因果', detail: '富裕家庭父母缺席导致童年孤独'}]->(b);

// ========== evt_relation: Event → Event ==========
MATCH (a:Event {id: 'evt_001'}), (b:Event {id: 'evt_002'}) MERGE (a)-[:evt_relation {type: '因果', detail: '酒店逃离后过马路遭遇车祸'}]->(b);
MATCH (a:Event {id: 'evt_002'}), (b:Event {id: 'evt_003'}) MERGE (a)-[:evt_relation {type: '因果', detail: '死亡后进入试炼系统'}]->(b);
MATCH (a:Event {id: 'evt_003'}), (b:Event {id: 'evt_004'}) MERGE (a)-[:evt_relation {type: '因果', detail: '开始第一个试炼灵魂进入陈默身体'}]->(b);
MATCH (a:Event {id: 'evt_004'}), (b:Event {id: 'evt_005'}) MERGE (a)-[:evt_relation {type: '包含', detail: '分支A·姐姐来电'}]->(b);
MATCH (a:Event {id: 'evt_004'}), (b:Event {id: 'evt_006'}) MERGE (a)-[:evt_relation {type: '包含', detail: '分支B·跳江BE'}]->(b);
MATCH (a:Event {id: 'evt_004'}), (b:Event {id: 'evt_007'}) MERGE (a)-[:evt_relation {type: '先后', detail: '灵魂挤入后发现转账记录'}]->(b);
MATCH (a:Event {id: 'evt_007'}), (b:Event {id: 'evt_008'}) MERGE (a)-[:evt_relation {type: '先后', detail: '删微信后步行回家'}]->(b);
MATCH (a:Event {id: 'evt_008'}), (b:Event {id: 'evt_009'}) MERGE (a)-[:evt_relation {type: '先后', detail: '回家后整理外表'}]->(b);
MATCH (a:Event {id: 'evt_009'}), (b:Event {id: 'evt_010'}) MERGE (a)-[:evt_relation {type: '先后', detail: '整理后重返代练'}]->(b);
MATCH (a:Event {id: 'evt_010'}), (b:Event {id: 'evt_012'}) MERGE (a)-[:evt_relation {type: '因果', detail: '代练引起关注后林梦提议直播'}]->(b);
MATCH (a:Event {id: 'evt_012'}), (b:Event {id: 'evt_013'}) MERGE (a)-[:evt_relation {type: '先后', detail: '直播后收到沈暮雪私信'}]->(b);
MATCH (a:Event {id: 'evt_013'}), (b:Event {id: 'evt_014'}) MERGE (a)-[:evt_relation {type: '因果', detail: '私信导致试训'}]->(b);
MATCH (a:Event {id: 'evt_014'}), (b:Event {id: 'evt_015'}) MERGE (a)-[:evt_relation {type: '因果', detail: '试训表现后约谈邀请加入二队'}]->(b);
MATCH (a:Event {id: 'evt_020'}), (b:Event {id: 'evt_021'}) MERGE (a)-[:evt_relation {type: '包含', detail: '爬山当天地铁返程'}]->(b);
MATCH (a:Event {id: 'evt_022'}), (b:Event {id: 'evt_023'}) MERGE (a)-[:evt_relation {type: '包含', detail: '漫展当天送回家'}]->(b);
MATCH (a:Event {id: 'evt_027'}), (b:Event {id: 'evt_028'}) MERGE (a)-[:evt_relation {type: '包含', detail: '选择苏晓禾路线结局'}]->(b);
MATCH (a:Event {id: 'evt_027'}), (b:Event {id: 'evt_029'}) MERGE (a)-[:evt_relation {type: '包含', detail: '选择林梦路线结局'}]->(b);
MATCH (a:Event {id: 'evt_027'}), (b:Event {id: 'evt_030'}) MERGE (a)-[:evt_relation {type: '包含', detail: '选择沈暮雪路线结局'}]->(b);
