MERGE (n:Character {id: 'NvCkQmFPFo'}) SET n.name = '陆择', n.gender = '男', n.description = '男主角，灵魂穿越者，渣男';
MERGE (n:Character {id: 'NvCkQmFPFp'}) SET n.name = '伊芙', n.gender = '女', n.description = '天使，灵魂引路人', n.character_tags = '天使天然呆';
MERGE (n:Character {id: 'NvCkQmFPFq'}) SET n.name = '陈默', n.gender = '男', n.description = '代练高手', n.character_tags = '舔狗,游戏高手,宅男';
MERGE (n:Character {id: 'NvCkQmFPFr'}) SET n.name = '温蔓青', n.gender = '女', n.description = '陈默前女友', n.character_tags = '绿茶婊';
MERGE (n:Character {id: 'NvCkQmFPFs'}) SET n.name = '苏晓禾', n.gender = '女', n.description = '运动康复者', n.character_tags = '运动,阳光,心思细腻';
MERGE (n:Character {id: 'NvCkQmFPFt'}) SET n.name = '林梦', n.gender = '女', n.description = '代练客户，网名"梦回峡谷"，富家千金', n.character_tags = '黏人,话痨';
MERGE (n:Character {id: 'NvCkQmFPFu'}) SET n.name = '沈暮雪', n.gender = '女', n.description = '星耀电竞战队经理', n.character_tags = '御姐,小资,外冷内热';
MERGE (n:Character {id: 'NvCkQmFPFv'}) SET n.name = '顾盈', n.gender = '女', n.description = '陆择一夜情对象', n.character_tags = '性感';
MERGE (n:Character {id: 'NvCkQmFPFw'}) SET n.name = '江烈', n.gender = '男', n.description = '星耀电竞战队队长';
MERGE (n:Location {id: 'NvCkQmFPGO'}) SET n.name = '酒店', n.description = '陆择和顾盈过夜的酒店';
MERGE (n:Location {id: 'NvCkQmFPGP'}) SET n.name = '马路', n.description = '陆择遭遇车祸的路口';
MERGE (n:Location {id: 'NvCkQmFPGQ'}) SET n.name = '长江大桥', n.description = '陈默跳江的地方';
MERGE (n:Location {id: 'NvCkQmFPGR'}) SET n.name = '八楼出租屋', n.description = '陈默的住所';
MERGE (n:Location {id: 'NvCkQmFPGS'}) SET n.name = '南滨路', n.description = '晨跑偶遇苏晓禾的地方';
MERGE (n:Location {id: 'NvCkQmFPGT'}) SET n.name = '星耀电竞基地', n.description = '星耀电竞战队训练基地';
MERGE (n:Location {id: 'NvCkQmFPGU'}) SET n.name = '咖啡店', n.description = '沈暮雪约见男主的咖啡店';
MERGE (n:Location {id: 'NvCkQmFPGV'}) SET n.name = '西餐厅', n.description = 'Day 11吃牛排的西餐厅';
MERGE (n:Location {id: 'NvCkQmFPGW'}) SET n.name = '超市', n.description = '苏晓禾拉男主去的超市';
MERGE (n:Location {id: 'NvCkQmFPGX'}) SET n.name = '漫展会场', n.description = 'Day 16漫展地点';
MERGE (n:Location {id: 'NvCkQmFPGY'}) SET n.name = '林梦家', n.description = '超级大平层空荡无人';
MERGE (n:Location {id: 'NvCkQmFPGZ'}) SET n.name = '路边摊', n.description = 'Day 18吃路边摊的地方';
MERGE (n:Event {id: 'NvCkQmFPFx'}) SET n.title = '陆择酒店醒来逃离', n.time = '开场', n.description = '陆择酒店醒来，顾盈正在洗漱准备离开（穿着男主的白衬衫），陆择用"手机没电"逃离', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPFy'}) SET n.title = '陆择车祸死亡', n.time = '开场', n.description = '过马路遭遇车祸死亡', n.type = '转折';
MERGE (n:Event {id: 'NvCkQmFPFz'}) SET n.title = '伊芙告知试炼规则', n.time = '开场', n.description = '伊芙告知试炼规则：六个试炼，每个30天，灵魂穿越拯救弱者', n.type = '交流';
MERGE (n:Event {id: 'NvCkQmFPG0'}) SET n.title = '陈默跳江陆择灵魂挤入', n.time = 'Day 0 深夜', n.description = '陈默长江大桥跳江，陆择灵魂挤入身体，翻回栏杆', n.type = '转折';
MERGE (n:Event {id: 'NvCkQmFPG1'}) SET n.title = '姐姐来电（分支A）', n.time = 'Day 0', n.description = '选择"再想想"→姐姐的电话打了过来（主线继续）', n.type = '转折';
MERGE (n:Event {id: 'NvCkQmFPG2'}) SET n.title = '跳江BE（分支B）', n.time = 'Day 0', n.description = '选择"跳江"→BE，很多人自发买吃的祭奠', n.type = '转折';
MERGE (n:Event {id: 'NvCkQmFPG3'}) SET n.title = '发现转账记录删除温蔓青', n.time = 'Day 0 深夜', n.description = '发现转账记录（66666元给温蔓青），删除温蔓青微信', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPG4'}) SET n.title = '步行回出租屋发现身体损耗', n.time = 'Day 0 凌晨', n.description = '步行回八楼出租屋，发现身体严重损耗', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPG5'}) SET n.title = '理发买衣吃面', n.time = 'Day 1', n.description = '理发、买平价新衣、吃重庆小面——身体在食物面前发抖', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPG6'}) SET n.title = '重返代练林梦成迷妹', n.time = 'Day 2', n.description = '重返代练，林梦点单，被实力折服变成小迷妹', n.type = '交流';
MERGE (n:Event {id: 'NvCkQmFPG7'}) SET n.title = '晨跑偶遇苏晓禾', n.time = 'Day 4', n.description = '南滨路晨跑偶遇苏晓禾，被指出跑步姿势不对可能会伤害膝盖', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPG8'}) SET n.title = '林梦提议直播', n.time = 'Day 5', n.description = '林梦提议做直播，首场峰值12000', n.type = '交流';
MERGE (n:Event {id: 'NvCkQmFPG9'}) SET n.title = '收到沈暮雪私信', n.time = 'Day 5 深夜', n.description = '下播后收到沈暮雪私信', n.type = '交流';
MERGE (n:Event {id: 'NvCkQmFPGA'}) SET n.title = '星耀试训与江烈冲突', n.time = 'Day 7', n.description = '星耀电竞试训，个人碾压但团队配合差，与江烈冲突', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGB'}) SET n.title = '沈暮雪邀请加入二队', n.time = 'Day 10', n.description = '沈暮雪在咖啡店约男主，邀请加入二队', n.type = '交流';
MERGE (n:Event {id: 'NvCkQmFPGC'}) SET n.title = '沈暮雪拉去西餐厅', n.time = 'Day 11', n.description = '沈暮雪加微信后看到签名"想吃肉"，拉男主去西餐厅吃牛排', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGD'}) SET n.title = '跑步遇雨去出租屋避雨', n.time = 'Day 13 上午', n.description = '跑步突然下雨，两人去陈默出租屋避雨', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGE'}) SET n.title = '苏晓禾拉去超市', n.time = 'Day 13 下午', n.description = '苏晓禾发现男主冰箱只有可乐和泡面，强行拉他去超市。她认真挑鸡蛋、青菜、牛奶。男主吐槽像老夫老妻，她耳朵红了但装没听见', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGF'}) SET n.title = '林梦对喷弹幕', n.time = 'Day 14', n.description = '林梦作为房管，和阴阳怪气的弹幕对喷', n.type = '交流';
MERGE (n:Event {id: 'NvCkQmFPGG'}) SET n.title = '爬山', n.time = 'Day 15 白天', n.description = '爬山，幻想苏晓禾穿瑜伽服，实际休闲服', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGH'}) SET n.title = '地铁苏晓禾睡着靠过来', n.time = 'Day 15 傍晚', n.description = '地铁返程，苏晓禾太累睡着，头轻轻靠过来', n.type = '状态变化';
MERGE (n:Event {id: 'NvCkQmFPGI'}) SET n.title = '漫展', n.time = 'Day 16 白天', n.description = '林梦拉男主去漫展，提前准备情侣角色但不敢直说。男主刚好抽到对应角色，她高兴得偷偷拍照', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGJ'}) SET n.title = '送林梦回家', n.time = 'Day 16 晚上', n.description = '漫展后送林梦回家——超级大平层，但没人、很安静、像酒店。她一边拆零食一边说：我小时候发烧，家里只有保姆。发朋友圈"今天超幸运"', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGK'}) SET n.title = '生病苏晓禾送吃的', n.time = 'Day 17', n.description = '生病发烧，苏晓禾送吃的', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGL'}) SET n.title = '路边摊', n.time = 'Day 18', n.description = '男主拉沈暮雪去路边摊，被辣出眼泪', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGM'}) SET n.title = '偷看苏晓禾工作约晚餐', n.time = 'Day 19', n.description = '偷偷去苏晓禾工作的地方看她，约晚餐', n.type = '行动';
MERGE (n:Event {id: 'NvCkQmFPGN'}) SET n.title = '三选一抉择', n.time = 'Day 22', n.description = '三个未接来电，陈默开启三选一，选择一个女主进行后续剧情', n.type = '转折';
MERGE (n:Info {id: 'NvCkQmFPGa'}) SET n.title = '灵魂穿越者系统规则', n.content = '灵魂穿越者能通过系统获取宿主近期的信息（暂定10天内），再久远的信息要通过环境叙事告诉玩家', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGb'}) SET n.title = '灵魂穿越者只能干预关键选择', n.content = '灵魂穿越者无法直接控制宿主的行为，只能在关键选择节点进行干预，关键选择节点也就是玩家的选择项', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGc'}) SET n.title = '试炼规则', n.content = '六个试炼，每个30天，灵魂穿越拯救弱者', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGd'}) SET n.title = '陆择一夜情后逃离车祸死亡', n.content = '陆择酒店醒来后用手机没电为借口逃离，过马路遭遇车祸死亡', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGe'}) SET n.title = '顾盈是陆择一夜情对象', n.content = '顾盈与陆择一夜情后准备离开，穿着男主的白衬衫', n.knowledge_level = 2;
MERGE (n:Info {id: 'NvCkQmFPGf'}) SET n.title = '陈默深夜跳江自杀', n.content = '陈默深夜在长江大桥跳江，被陆择灵魂挤入身体翻回栏杆', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGg'}) SET n.title = '陈默给温蔓青转账66666元', n.content = '陈默的转账记录显示给温蔓青转了66666元', n.knowledge_level = 2;
MERGE (n:Info {id: 'NvCkQmFPGh'}) SET n.title = '温蔓青是陈默前女友', n.content = '温蔓青是陈默的前女友，已被删除微信', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGi'}) SET n.title = '陈默身体严重损耗', n.content = '陈默的身体严重损耗，吃重庆小面时身体在食物面前发抖', n.knowledge_level = 2;
MERGE (n:Info {id: 'NvCkQmFPGj'}) SET n.title = '林梦是富家千金', n.content = '林梦是代练客户，网名"梦回峡谷"，富家千金，住超级大平层', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGk'}) SET n.title = '陈默有直播天赋', n.content = '林梦提议做直播，首场峰值12000，展现直播天赋', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGl'}) SET n.title = '苏晓禾是运动康复专业人士', n.content = '苏晓禾是运动康复者，能指出跑步姿势不对可能会伤害膝盖', n.knowledge_level = 2;
MERGE (n:Info {id: 'NvCkQmFPGm'}) SET n.title = '陈默实力碾压但团队配合差', n.content = '星耀电竞试训中陈默个人碾压但团队配合差，与队长江烈冲突', n.knowledge_level = 2;
MERGE (n:Info {id: 'NvCkQmFPGn'}) SET n.title = '沈暮雪是星耀电竞经理', n.content = '沈暮雪是星耀电竞战队经理，看直播后私信男主', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGo'}) SET n.title = '江烈是星耀电竞队长', n.content = '江烈是星耀电竞战队队长，试训中与陈默冲突', n.knowledge_level = 1;
MERGE (n:Info {id: 'NvCkQmFPGp'}) SET n.title = '林梦家庭背景孤独', n.content = '林梦家是超级大平层但空荡无人像酒店，她说小时候发烧家里只有保姆', n.knowledge_level = 2;
MERGE (n:Info {id: 'NvCkQmFPGq'}) SET n.title = '林梦提前准备漫展情侣角色', n.content = '林梦提前准备情侣角色但不敢直说，男主刚好抽到对应角色她高兴得偷偷拍照', n.knowledge_level = 2;
MERGE (n:Info {id: 'NvCkQmFPGr'}) SET n.title = '陈默有姐姐', n.content = '分支A中选择再想想后姐姐的电话打了过来，暗示陈默有姐姐', n.knowledge_level = 2;
MERGE (n:Info {id: 'NvCkQmFPGs'}) SET n.title = '苏晓禾认真挑食材暗示亲密', n.content = '苏晓禾发现男主冰箱只有可乐和泡面强行拉去超市，认真挑鸡蛋青菜牛奶，男主吐槽像老夫老妻她耳朵红了', n.knowledge_level = 2;
MATCH (a:Character {id: 'NvCkQmFPFv'}), (b:Character {id: 'NvCkQmFPFo'}) MERGE (a)-[:relation {type: '一夜情', detail: '陆择与顾盈的一夜情'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFr'}), (b:Character {id: 'NvCkQmFPFq'}) MERGE (a)-[:relation {type: '前任', detail: '已分手'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Character {id: 'NvCkQmFPFq'}) MERGE (a)-[:relation {type: '客户', detail: '代练客户兼小迷妹'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Character {id: 'NvCkQmFPFq'}) MERGE (a)-[:relation {type: '招募', detail: '经理招募选手', start_time: 'Day 5'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFw'}), (b:Character {id: 'NvCkQmFPFu'}) MERGE (a)-[:relation {type: '同事', detail: '队长与经理'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFo'}), (b:Event {id: 'NvCkQmFPFx'}) MERGE (a)-[:involved {role: '当事人', detail: '酒店醒来逃离'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFv'}), (b:Event {id: 'NvCkQmFPFx'}) MERGE (a)-[:involved {role: '参与者', detail: '洗漱准备离开'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFo'}), (b:Event {id: 'NvCkQmFPFy'}) MERGE (a)-[:involved {role: '受害者', detail: '过马路遭遇车祸死亡'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFp'}), (b:Event {id: 'NvCkQmFPFz'}) MERGE (a)-[:involved {role: '当事人', detail: '告知试炼规则'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFo'}), (b:Event {id: 'NvCkQmFPFz'}) MERGE (a)-[:involved {role: '当事人', detail: '被告知试炼规则'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG0'}) MERGE (a)-[:involved {role: '当事人', detail: '跳江者'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFo'}), (b:Event {id: 'NvCkQmFPG0'}) MERGE (a)-[:involved {role: '当事人', detail: '灵魂挤入身体'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG1'}) MERGE (a)-[:involved {role: '当事人', detail: '接到姐姐电话'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG2'}) MERGE (a)-[:involved {role: '当事人', detail: '跳江BE'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG3'}) MERGE (a)-[:involved {role: '当事人', detail: '发现转账记录并删除微信'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFr'}), (b:Event {id: 'NvCkQmFPG3'}) MERGE (a)-[:involved {role: '涉及者', detail: '转账收款方'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG4'}) MERGE (a)-[:involved {role: '当事人', detail: '步行回出租屋'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG5'}) MERGE (a)-[:involved {role: '当事人', detail: '理发买衣吃面'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG6'}) MERGE (a)-[:involved {role: '当事人', detail: '重返代练'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'NvCkQmFPG6'}) MERGE (a)-[:involved {role: '参与者', detail: '点单被实力折服成迷妹'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG7'}) MERGE (a)-[:involved {role: '当事人', detail: '晨跑偶遇'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'NvCkQmFPG7'}) MERGE (a)-[:involved {role: '参与者', detail: '指出跑步姿势不对'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG8'}) MERGE (a)-[:involved {role: '当事人', detail: '做直播'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'NvCkQmFPG8'}) MERGE (a)-[:involved {role: '参与者', detail: '提议做直播'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPG9'}) MERGE (a)-[:involved {role: '当事人', detail: '收到私信'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'NvCkQmFPG9'}) MERGE (a)-[:involved {role: '当事人', detail: '发出私信'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGA'}) MERGE (a)-[:involved {role: '当事人', detail: '参加试训'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'NvCkQmFPGA'}) MERGE (a)-[:involved {role: '参与者', detail: '安排试训'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFw'}), (b:Event {id: 'NvCkQmFPGA'}) MERGE (a)-[:involved {role: '参与者', detail: '试训冲突'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGB'}) MERGE (a)-[:involved {role: '当事人', detail: '被邀请加入二队'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'NvCkQmFPGB'}) MERGE (a)-[:involved {role: '当事人', detail: '邀请加入二队'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGC'}) MERGE (a)-[:involved {role: '当事人', detail: '被拉去西餐厅'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'NvCkQmFPGC'}) MERGE (a)-[:involved {role: '当事人', detail: '拉去西餐厅吃牛排'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGD'}) MERGE (a)-[:involved {role: '当事人', detail: '避雨'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'NvCkQmFPGD'}) MERGE (a)-[:involved {role: '参与者', detail: '一起避雨'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGE'}) MERGE (a)-[:involved {role: '当事人', detail: '被拉去超市'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'NvCkQmFPGE'}) MERGE (a)-[:involved {role: '当事人', detail: '拉去超市挑食材'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'NvCkQmFPGF'}) MERGE (a)-[:involved {role: '当事人', detail: '房管对喷弹幕'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGG'}) MERGE (a)-[:involved {role: '当事人', detail: '爬山'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'NvCkQmFPGG'}) MERGE (a)-[:involved {role: '参与者', detail: '一起爬山'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGH'}) MERGE (a)-[:involved {role: '当事人', detail: '地铁返程'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'NvCkQmFPGH'}) MERGE (a)-[:involved {role: '当事人', detail: '睡着靠过来'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGI'}) MERGE (a)-[:involved {role: '当事人', detail: '去漫展'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'NvCkQmFPGI'}) MERGE (a)-[:involved {role: '当事人', detail: '拉去漫展准备情侣角色'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGJ'}) MERGE (a)-[:involved {role: '当事人', detail: '送林梦回家'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'NvCkQmFPGJ'}) MERGE (a)-[:involved {role: '当事人', detail: '被送回家'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGK'}) MERGE (a)-[:involved {role: '当事人', detail: '生病发烧'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'NvCkQmFPGK'}) MERGE (a)-[:involved {role: '参与者', detail: '送吃的'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGL'}) MERGE (a)-[:involved {role: '当事人', detail: '拉沈暮雪去路边摊'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'NvCkQmFPGL'}) MERGE (a)-[:involved {role: '参与者', detail: '被拉去路边摊'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGM'}) MERGE (a)-[:involved {role: '当事人', detail: '偷看苏晓禾工作'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'NvCkQmFPGM'}) MERGE (a)-[:involved {role: '参与者', detail: '被偷看'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'NvCkQmFPGN'}) MERGE (a)-[:involved {role: '当事人', detail: '三选一抉择'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'NvCkQmFPGN'}) MERGE (a)-[:involved {role: '涉及者', detail: '候选女主'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'NvCkQmFPGN'}) MERGE (a)-[:involved {role: '涉及者', detail: '候选女主'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'NvCkQmFPGN'}) MERGE (a)-[:involved {role: '涉及者', detail: '候选女主'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPFx'}), (b:Location {id: 'NvCkQmFPGO'}) MERGE (a)-[:occurred_at {detail: '陆择和顾盈过夜的酒店'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPFy'}), (b:Location {id: 'NvCkQmFPGP'}) MERGE (a)-[:occurred_at {detail: '车祸发生的路口'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG0'}), (b:Location {id: 'NvCkQmFPGQ'}) MERGE (a)-[:occurred_at {detail: '跳江地点'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG4'}), (b:Location {id: 'NvCkQmFPGR'}) MERGE (a)-[:occurred_at {detail: '回到住所'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG7'}), (b:Location {id: 'NvCkQmFPGS'}) MERGE (a)-[:occurred_at {detail: '晨跑偶遇地点'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGA'}), (b:Location {id: 'NvCkQmFPGT'}) MERGE (a)-[:occurred_at {detail: '试训地点'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGB'}), (b:Location {id: 'NvCkQmFPGU'}) MERGE (a)-[:occurred_at {detail: '约见地点'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGC'}), (b:Location {id: 'NvCkQmFPGV'}) MERGE (a)-[:occurred_at {detail: '吃牛排地点'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGD'}), (b:Location {id: 'NvCkQmFPGR'}) MERGE (a)-[:occurred_at {detail: '避雨地点'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGE'}), (b:Location {id: 'NvCkQmFPGW'}) MERGE (a)-[:occurred_at {detail: '买菜地点'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGI'}), (b:Location {id: 'NvCkQmFPGX'}) MERGE (a)-[:occurred_at {detail: '漫展地点'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGJ'}), (b:Location {id: 'NvCkQmFPGY'}) MERGE (a)-[:occurred_at {detail: '送回家'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGL'}), (b:Location {id: 'NvCkQmFPGZ'}) MERGE (a)-[:occurred_at {detail: '吃路边摊地点'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Location {id: 'NvCkQmFPGR'}) MERGE (a)-[:at {type: '居住', detail: '陈默的出租屋'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Location {id: 'NvCkQmFPGT'}) MERGE (a)-[:at {type: '工作', detail: '星耀电竞经理'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFw'}), (b:Location {id: 'NvCkQmFPGT'}) MERGE (a)-[:at {type: '工作', detail: '星耀电竞队长'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Location {id: 'NvCkQmFPGY'}) MERGE (a)-[:at {type: '居住', detail: '超级大平层'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFp'}), (b:Info {id: 'NvCkQmFPGa'}) MERGE (a)-[:link {type: '涉及', detail: '伊芙解释系统规则', time: '开场'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFp'}), (b:Info {id: 'NvCkQmFPGb'}) MERGE (a)-[:link {type: '涉及', detail: '伊芙解释干预规则', time: '开场'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFp'}), (b:Info {id: 'NvCkQmFPGc'}) MERGE (a)-[:link {type: '涉及', detail: '伊芙告知试炼规则', time: '开场'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFo'}), (b:Info {id: 'NvCkQmFPGd'}) MERGE (a)-[:link {type: '涉及', detail: '陆择车祸死亡', time: '开场'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFv'}), (b:Info {id: 'NvCkQmFPGe'}) MERGE (a)-[:link {type: '涉及', detail: '顾盈身份', time: '开场'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Info {id: 'NvCkQmFPGf'}) MERGE (a)-[:link {type: '涉及', detail: '陈默跳江', time: 'Day 0'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG3'}), (b:Info {id: 'NvCkQmFPGg'}) MERGE (a)-[:link {type: '涉及', detail: '转账记录', time: 'Day 0'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFr'}), (b:Info {id: 'NvCkQmFPGh'}) MERGE (a)-[:link {type: '涉及', detail: '温蔓青身份', time: 'Day 0'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG4'}), (b:Info {id: 'NvCkQmFPGi'}) MERGE (a)-[:link {type: '涉及', detail: '发现身体损耗', time: 'Day 0'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Info {id: 'NvCkQmFPGj'}) MERGE (a)-[:link {type: '涉及', detail: '林梦身份', time: 'Day 2'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG8'}), (b:Info {id: 'NvCkQmFPGk'}) MERGE (a)-[:link {type: '涉及', detail: '直播天赋', time: 'Day 5'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Info {id: 'NvCkQmFPGl'}) MERGE (a)-[:link {type: '涉及', detail: '苏晓禾专业背景', time: 'Day 4'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGA'}), (b:Info {id: 'NvCkQmFPGm'}) MERGE (a)-[:link {type: '涉及', detail: '试训表现', time: 'Day 7'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Info {id: 'NvCkQmFPGn'}) MERGE (a)-[:link {type: '涉及', detail: '沈暮雪身份', time: 'Day 5'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFw'}), (b:Info {id: 'NvCkQmFPGo'}) MERGE (a)-[:link {type: '涉及', detail: '江烈身份', time: 'Day 7'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGJ'}), (b:Info {id: 'NvCkQmFPGp'}) MERGE (a)-[:link {type: '涉及', detail: '林梦家庭背景', time: 'Day 16'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGI'}), (b:Info {id: 'NvCkQmFPGq'}) MERGE (a)-[:link {type: '涉及', detail: '林梦准备情侣角色', time: 'Day 16'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG1'}), (b:Info {id: 'NvCkQmFPGr'}) MERGE (a)-[:link {type: '涉及', detail: '姐姐来电暗示', time: 'Day 0'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGE'}), (b:Info {id: 'NvCkQmFPGs'}) MERGE (a)-[:link {type: '涉及', detail: '苏晓禾挑食材', time: 'Day 13'}]->(b);
MATCH (a:Info {id: 'NvCkQmFPGg'}), (b:Info {id: 'NvCkQmFPGf'}) MERGE (a)-[:link {type: '因果', detail: '转账→跳江动机'}]->(b);
MATCH (a:Info {id: 'NvCkQmFPGh'}), (b:Info {id: 'NvCkQmFPGg'}) MERGE (a)-[:link {type: '因果', detail: '恋爱关系→转账'}]->(b);
MATCH (a:Info {id: 'NvCkQmFPGa'}), (b:Info {id: 'NvCkQmFPGb'}) MERGE (a)-[:link {type: '因果', detail: '系统规则→干预限制'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPFx'}), (b:Event {id: 'NvCkQmFPFy'}) MERGE (a)-[:evt_relation {type: '因果', detail: '逃离酒店→过马路车祸'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPFy'}), (b:Event {id: 'NvCkQmFPFz'}) MERGE (a)-[:evt_relation {type: '因果', detail: '死亡→进入试炼'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPFz'}), (b:Event {id: 'NvCkQmFPG0'}) MERGE (a)-[:evt_relation {type: '因果', detail: '试炼开始→灵魂穿越到陈默'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG0'}), (b:Event {id: 'NvCkQmFPG1'}) MERGE (a)-[:evt_relation {type: '包含', detail: '跳江→分支A姐姐来电'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG0'}), (b:Event {id: 'NvCkQmFPG2'}) MERGE (a)-[:evt_relation {type: '包含', detail: '跳江→分支B跳江BE'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG0'}), (b:Event {id: 'NvCkQmFPG3'}) MERGE (a)-[:evt_relation {type: '先后', detail: '跳江后查看手机'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG3'}), (b:Event {id: 'NvCkQmFPG4'}) MERGE (a)-[:evt_relation {type: '先后', detail: '删微信后步行回家'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG4'}), (b:Event {id: 'NvCkQmFPG5'}) MERGE (a)-[:evt_relation {type: '先后', detail: '回家后第二天出门'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG5'}), (b:Event {id: 'NvCkQmFPG6'}) MERGE (a)-[:evt_relation {type: '先后', detail: '整理形象后重返代练'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG6'}), (b:Event {id: 'NvCkQmFPG7'}) MERGE (a)-[:evt_relation {type: '先后', detail: '代练后开始晨跑'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG7'}), (b:Event {id: 'NvCkQmFPG8'}) MERGE (a)-[:evt_relation {type: '先后', detail: '偶遇后继续发展'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG8'}), (b:Event {id: 'NvCkQmFPG9'}) MERGE (a)-[:evt_relation {type: '因果', detail: '直播引来沈暮雪关注'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG9'}), (b:Event {id: 'NvCkQmFPGA'}) MERGE (a)-[:evt_relation {type: '因果', detail: '私信→试训邀请'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGA'}), (b:Event {id: 'NvCkQmFPGB'}) MERGE (a)-[:evt_relation {type: '因果', detail: '试训→邀请加入二队'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGB'}), (b:Event {id: 'NvCkQmFPGC'}) MERGE (a)-[:evt_relation {type: '先后', detail: '加入后社交'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGC'}), (b:Event {id: 'NvCkQmFPGD'}) MERGE (a)-[:evt_relation {type: '先后'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGD'}), (b:Event {id: 'NvCkQmFPGE'}) MERGE (a)-[:evt_relation {type: '先后'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGE'}), (b:Event {id: 'NvCkQmFPGF'}) MERGE (a)-[:evt_relation {type: '先后'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGF'}), (b:Event {id: 'NvCkQmFPGG'}) MERGE (a)-[:evt_relation {type: '先后'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGG'}), (b:Event {id: 'NvCkQmFPGH'}) MERGE (a)-[:evt_relation {type: '先后', detail: '爬山后返程'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGH'}), (b:Event {id: 'NvCkQmFPGI'}) MERGE (a)-[:evt_relation {type: '先后'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGI'}), (b:Event {id: 'NvCkQmFPGJ'}) MERGE (a)-[:evt_relation {type: '先后', detail: '漫展后送回家'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGJ'}), (b:Event {id: 'NvCkQmFPGK'}) MERGE (a)-[:evt_relation {type: '先后'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGK'}), (b:Event {id: 'NvCkQmFPGL'}) MERGE (a)-[:evt_relation {type: '先后'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGL'}), (b:Event {id: 'NvCkQmFPGM'}) MERGE (a)-[:evt_relation {type: '先后'}]->(b);
MATCH (a:Event {id: 'NvCkQmFPGM'}), (b:Event {id: 'NvCkQmFPGN'}) MERGE (a)-[:evt_relation {type: '先后', detail: '感情线汇聚到抉择'}]->(b);
